# Generated by Django 5.1.1 on 2025-01-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='internal_invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
