# Generated by Django 5.1.1 on 2025-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_invoice_internal_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='party_1_amount',
            new_name='party_amount',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='party_1',
            new_name='party_name',
        ),
        migrations.RemoveField(
            model_name='party',
            name='party_2',
        ),
        migrations.RemoveField(
            model_name='party',
            name='party_2_amount',
        ),
        migrations.AddField(
            model_name='party',
            name='party_percentage',
            field=models.CharField(blank=True, choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10')], max_length=10, null=True),
        ),
    ]
